language: php

php:
  - 5.5

before_script:
  - composer install --prefer-dist --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: matthiasnoback@gmail.com